### ISSUE TITLE
any limit on .signAllTransactions()?

### ISSUE THREAD

**Issue by neerajajaja** [phantom-labs/docs#20]
hey, would like to know if there is any limit on the number of transactions i can sign with .signAllTransactions()?

**Comment by AntonKrutikov** [comment]
Have issue with this in example like buying many NFTs at once - with 3 transactions it properly show balance changes including '+NFT', but with 4+ it's always 'unable to fetch balance change'. Also with ignoring this error and signing, next sending this transactions - them executes. In solfare all transaction shown properly...

**Comment by bfriel** [comment]
At this time, Phantom does not put a limit on the number of txs that can be signed with `signAllTransactions`. We have seen that the app may become unresponsive above 80 txs, likely due to the payload size becoming too large. If and when we do put a cap on this, we will document it.

@AntonKrutikov the simulation issue you're describing is due to a Solana JSON-RPC constraint with how we are simulating transactions. When multiple transactions are present, we attempt to simulate the transactions serially, rather than in parallel to each other, so that we can simulate the actual end state to the best of our ability. As you pointed out, this can cause issues when too many transactions are present. We are currently working on a fix for this.

**Comment by gigigaz** [comment]
@bfriel now we have limit, right?
