### ISSUE TITLE
Possible collection of user data

### ISSUE THREAD

**Issue by Antttezy** [phantom-labs/docs#28]
Interacts with on-chain program DeJBGdMFa1uynnnKiwrVioatTuHmNLpyFKnmB5kaFdzQ while it should just create a token account and transfer token there. Nothing more
![image](https://user-images.githubusercontent.com/66439483/159985326-10d096ac-d987-416d-acdb-a598d55d261f.png)

**Comment by bfriel** [comment]
This is a custom deployment of the Serum [Assert Owner Program](https://github.com/project-serum/serum-dex/tree/6138ca98280f6433deecde560f3d23cc4a749bae/assert-owner). We deployed this ourselves because Serum's program was not available on Devnet. More info in our [FAQ Section](https://docs.phantom.app/resources/faq#why-does-phantom-prepend-an-additional-instruction-on-standard-spl-token-transfers)
